const ORDER_CONFIG = {
  batch: {
    number: 6,
    // Owner approved August 10, 2026. Customer reminders remain separately gated.
    published: true,
    remindersEnabled: true,
    deliveryDate: 'Saturday, August 15, 2026',
    cutoffIso: '2026-08-12T18:00:00-05:00',
    cutoffLabel: 'Wednesday at 6:00 PM CT',
    labelProduction: { madeDate: '2026-08-14', useByDate: '2026-08-17', batchId: 'B6-0814' },
  },
  policies: {
    minimumOrder: 60,
    freeDeliveryThreshold: 85,
    deliveryFee: 9.99,
    deliveryZones: {
      pickup: {
        id: 'pickup',
        label: 'Pickup',
        city: 'Frisco',
        state: 'TX',
        minimumOrder: 60,
        freeDeliveryThreshold: 60,
        deliveryFee: 0,
      },
      core: {
        id: 'core',
        label: 'Local Delivery',
        minimumOrder: 60,
        freeDeliveryThreshold: 85,
        deliveryFee: 9.99,
      },
      regional: {
        id: 'regional',
        label: 'Regional Delivery',
        minimumOrder: 80,
        freeDeliveryThreshold: 125,
        deliveryFee: 12.99,
      },
      extended: {
        id: 'extended',
        label: 'Extended Delivery',
        minimumOrder: 100,
        freeDeliveryThreshold: 150,
        deliveryFee: 14.99,
      },
    },
    maxQtyPerItem: 50,
    maxTotalItems: 250,
  },
  promotions: { remote: true, codes: [] },
  prices: {
    standard: { lean: 10.99, bulk: 12.99 },
    beef: { lean: 13.99, bulk: 15.99 },
    premium: { lean: 21.99, bulk: 26.99 },
    dessert: { single: 6.99 },
    addon: { single: 6.99 },
  },
  plannerOnly: [
    { id: 'p1', name: 'Premium NY Strip Steak', category: 'premium', plannerOnly: true },
  ],
  menu: {
    breakfasts: [
      { id: 'b1', name: 'PRPD Beef Bacon Breakfast Sandwich', category: 'beef', laterWeek: true,
        description: 'Beef bacon, an egg-and-egg-white patty, cheese, and a PRPD Sweet Heat cup. Lean includes one sandwich with breakfast potatoes; Bulk includes two sandwiches with no potatoes.',
        macros: { cal: 600, protein: 36, carbs: 70, fiber: 4, fat: 20 }, bulkMacros: { cal: 860, protein: 65, carbs: 70, fiber: 2, fat: 35 }, image: '' },
      { id: 'b2', name: 'French Toast', category: 'standard',
        description: 'Protein French toast with fruit, whipped cream, and sugar-free maple syrup.',
        macros: { cal: 520, protein: 34, carbs: 76, fiber: 6, fat: 9 }, bulkMacros: { cal: 670, protein: 45, carbs: 96, fiber: 7, fat: 12 }, image: '/assets/images/meals/menu/french-toast.jpg' },
      { id: 'b3', name: 'Breakfast Quesadilla', category: 'standard',
        description: 'Seasoned chicken, a measured egg-and-egg-white base, and cheese in high-fiber tortillas.',
        macros: { cal: 465, protein: 61, carbs: 41, fiber: 30, fat: 17 }, bulkMacros: { cal: 655, protein: 84, carbs: 65, fiber: 56, fat: 24 }, image: '/assets/images/meals/menu/breakfast-quesadilla-lean.jpg' },
      { id: 'b4', name: 'Grilled Cheese Breakfast Burrito', category: 'beef', laterWeek: true,
        description: 'Seasoned beef, eggs, egg whites, cheese, and onion in grilled high-fiber tortillas.',
        macros: { cal: 480, protein: 55, carbs: 45, fiber: 31, fat: 20 }, bulkMacros: { cal: 675, protein: 79, carbs: 69, fiber: 57, fat: 27 }, image: '/assets/images/meals/menu/grilled-cheese-breakfast-burrito-bulk.jpg' },
    ],
    mains: [
      { id: 'm1', name: 'Loaded Beef Cottage Pie', category: 'beef', displayCategory: 'Beef', laterWeek: true,
        description: 'Seasoned beef and vegetables under Betty Crocker mashed potatoes and mozzarella, with PRPD Sweet Heat sauce.',
        macros: { cal: 710, protein: 51, carbs: 60, fiber: 6, fat: 30 }, bulkMacros: { cal: 850, protein: 64, carbs: 67, fiber: 8, fat: 36 }, image: '' },
      { id: 'm2', name: 'Hot Honey Chicken Sliders', category: 'standard',
        description: 'Sriracha hot-honey chicken, cheese, house refrigerator pickles, and onion on soft bakery rolls.',
        macros: { cal: 610, protein: 40, carbs: 81, fiber: 2, fat: 14 }, bulkMacros: { cal: 820, protein: 55, carbs: 108, fiber: 3, fat: 19 }, image: '' },
      { id: 'm3', name: 'Loaded Buffalo Chicken Potato', category: 'standard', laterWeek: true,
        description: 'Buffalo chicken over a loaded roasted potato with broccoli.',
        macros: { cal: 520, protein: 48, carbs: 40, fiber: 6, fat: 18 }, bulkMacros: { cal: 660, protein: 68, carbs: 40, fiber: 6, fat: 25 }, image: '/assets/images/meals/menu/loaded-buffalo-chicken-potato.jpg' },
      { id: 'm4', name: 'Beef Seekh Kabab Shawarma', category: 'beef', displayCategory: 'Beef',
        description: 'Seasoned beef seekh, fresh salad, drained house refrigerator pickles, and garlic yogurt sauce in shawarma bread.',
        macros: { cal: 575, protein: 44, carbs: 56, fiber: 2, fat: 17 }, bulkMacros: { cal: 770, protein: 56, carbs: 81, fiber: 2, fat: 21 }, image: '/assets/images/meals/menu/shawarma.jpg' },
      { id: 'm5', name: 'Harissa Honey Chicken', category: 'standard', laterWeek: true,
        description: 'Sweet-spicy harissa honey chicken with basmati rice and roasted broccoli.',
        macros: { cal: 580, protein: 44, carbs: 60, fiber: 4, fat: 18 }, bulkMacros: { cal: 820, protein: 65, carbs: 79, fiber: 5, fat: 26 }, image: '' },
      { id: 'm6', name: 'Mexican Streetcorn Chicken Bowl', category: 'standard',
        description: 'Seasoned chicken, basmati rice, and creamy street corn with peppers, jalapeno, cotija, lime, and cilantro.',
        macros: { cal: 595, protein: 48, carbs: 55, fiber: 3, fat: 21 }, bulkMacros: { cal: 790, protein: 65, carbs: 72, fiber: 4, fat: 27 }, image: '/assets/images/meals/menu/mexican-streetcorn-chicken-bowl-v2.jpg' },
      { id: 'm7', name: 'Garlic Butter Shrimp + Rice', category: 'beef', displayCategory: 'Seafood',
        description: 'Garlic-butter shrimp with basmati rice, peas and carrots, zucchini, and lemon.',
        macros: { cal: 460, protein: 43, carbs: 56, fiber: 5, fat: 7 }, bulkMacros: { cal: 615, protein: 58, carbs: 74, fiber: 6, fat: 10 }, image: '/assets/images/meals/menu/garlic-butter-shrimp.jpg' },
      { id: 'm8', name: 'BBQ Chicken Mac & Cheese', category: 'standard', laterWeek: true,
        description: 'BBQ chicken with high-protein macaroni and cheese and fat-free mozzarella.',
        macros: { cal: 525, protein: 59, carbs: 37, fiber: 3, fat: 16 }, bulkMacros: { cal: 700, protein: 81, carbs: 44, fiber: 3, fat: 22 }, image: '/assets/images/meals/menu/bbq-chicken-mac-and-cheese-lean.jpg' },
    ],
    desserts: [
      { id: 'd1', name: 'Chocolate-Dipped Cookie Dough Balls', category: 'dessert', description: 'Three protein cookie-dough balls with a measured chocolate coating.', macros: { cal: 520, protein: 38, carbs: 55, fiber: 6, fat: 16 }, image: '' },
      { id: 'd2', name: 'Chocolate Oreo Mousse', category: 'dessert', description: 'Chocolate protein mousse finished with Oreo Thins.', macros: { cal: 290, protein: 38, carbs: 30, fiber: 5, fat: 5 }, image: '/assets/images/meals/menu/chocolate-oreo-mousse.jpg' },
      { id: 'd3', name: 'Baked Strawberry-Lemon Protein Cheesecake Square', category: 'dessert', description: 'A baked strawberry-lemon protein cheesecake square with a real cheesecake texture.', macros: { cal: 225, protein: 14, carbs: 17, fiber: 1, fat: 11 }, image: '' },
    ],
    addons: [
      { id: 'a1', name: 'PRPD Protein Box', category: 'addon', price: 7.99, description: 'Two eggs, halal beef breakfast slices, cheese, a whole mini apple, cucumber, and house jalapeno-lemon yogurt dip.', macros: { cal: 355, protein: 29, carbs: 15, fiber: 2, fat: 20 }, image: '' },
      { id: 'a2', name: 'Mini Chicken Snack Wrap', category: 'addon', price: 7.99, description: 'Two high-fiber tortillas with seasoned chicken, cheese, fresh chopped salad, and house sauce.', macros: { cal: 325, protein: 41, carbs: 29, fiber: 23, fat: 13 }, image: '' },
      { id: 'a3', name: 'Strawberry Protein Overnight Oats', category: 'addon', price: 6.99, description: 'Strawberry protein overnight oats with Greek yogurt, chia, and honey in one 12 oz cup.', macros: { cal: 360, protein: 35, carbs: 45, fiber: 7, fat: 5 }, image: '' },
    ],
  },
};

if (typeof window !== 'undefined') window.PRPD_ORDER_CONFIG = ORDER_CONFIG;
if (typeof module !== 'undefined' && module.exports) module.exports = ORDER_CONFIG;
