(function (root, factory) {
  const data = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = data;
  if (root) root.PRPD_GROCERY_CATALOG = data;
})(typeof window !== 'undefined' ? window : globalThis, function () {
  const g = (packageSize, price, packageLabel, store = 'Planning price', confidence = 'planning', query = '') => ({ packageSize, price, packageLabel, store, confidence, query });
  const catalog = {
    egg: g(12, 1.47, '12-count carton', 'Walmart reference', 'planning', 'large eggs 12 count'),
    egg_white: g(907, 4.87, '32 oz carton', 'Walmart reference', 'planning', 'Great Value liquid egg whites 32 oz'),
    cottage: g(1361, 7.96, '48 oz Daisy tub', 'Walmart receipt 2026-07-16', 'verified', 'Daisy cottage cheese 48 oz'),
    mozzarella: g(2268, 10, '5 lb bag', 'PRPD confirmed', 'verified', 'fat free shredded mozzarella 5 lb'),
    spinach: g(227, 2.48, '8 oz bag', 'Local planning price', 'planning'),
    tomato: g(454, 0.97, '1 lb', 'Walmart receipt 2026-07-16', 'verified'),
    onion: g(454, 0.98, '1 lb', 'Local planning price', 'planning'),
    jalapeno: g(454, 1.32, '1 lb', 'Walmart receipt 2026-07-16', 'verified'),
    potato: g(2268, 4.95, '5 lb bag', 'Local planning price', 'planning'),
    avocado_oil: g(750, 8, '25 fl oz bottle', 'Earlier PRPD price', 'legacy'),
    salt: g(737, 0.67, '26 oz canister', 'Local planning price', 'planning'),
    fairlife_milk: g(1538, 5, '52 fl oz bottle', 'PRPD confirmed', 'verified'),
    whey: g(663, 32.5, '17-serving tub', 'PRPD confirmed midpoint', 'verified'),
    brown_sugar: g(907, 2.24, '2 lb bag', 'Local planning price', 'planning'),
    vanilla: g(59, 4.98, '2 fl oz bottle', 'Local planning price', 'planning'),
    cinnamon: g(71, 1.24, '2.5 oz bottle', 'Local planning price', 'planning'),
    bread_slice: g(18, 3.38, 'Italian loaf / about 18 slices', 'Walmart receipt 2026-07-16', 'verified', 'Pepperidge Farm Italian bread'),
    strawberry: g(454, 2.52, '1 lb clamshell', 'Walmart receipt 2026-07-16', 'verified'),
    banana: g(454, 0.50, '1 lb', 'Walmart receipt 2026-07-16', 'verified'),
    whipped_cream: g(184, 3.48, '6.5 oz can', 'Local planning price', 'planning'),
    maple_syrup: g(710, 2.78, '24 fl oz bottle', 'Local planning price', 'planning'),
    chicken_thigh_raw: g(18143.7, 143.60, '40 lb case', 'Restaurant Depot receipt 2026-07-16', 'verified'),
    small_tortilla: g(16, 10, '16-count pack', 'PRPD confirmed', 'verified'),
    large_tortilla: g(16, 10, '16-count pack', 'PRPD confirmed', 'verified'),
    fage: g(907, 3.28, '32 oz tub', 'Walmart receipt 2026-07-16', 'verified', 'Great Value plain nonfat Greek yogurt 32 oz'),
    salsa: g(454, 3, '16 oz jar', 'Earlier PRPD price', 'legacy'),
    beef_90_raw: g(453.592, 5.5, '1 lb', 'PRPD confirmed', 'verified'),
    tomato_paste: g(170, 1, '6 oz can', 'Earlier PRPD price', 'legacy'),
    broth: g(907, 2, '32 oz carton', 'Earlier PRPD price', 'legacy'),
    rice_dry: g(9072, 13, '20 lb bag', 'PRPD confirmed', 'verified'),
    butter: g(454, 4.87, '1 lb box', 'Earlier PRPD price', 'legacy'),
    lemon: g(48, 0.68, '1 lemon / about 48g juice', 'Walmart receipt 2026-07-16', 'verified'),
    garlic: g(50, 0.5, '1 bulb / about 50g usable', 'Local planning price', 'planning'),
    ginger: g(454, 3.97, '1 lb', 'Walmart receipt 2026-07-16', 'verified'),
    lettuce: g(500, 2.28, '1 head / about 500g usable', 'Walmart receipt 2026-07-16', 'verified'),
    light_mayo: g(850, 4.98, '30 oz jar', 'Walmart receipt 2026-07-16', 'verified'),
    broccoli: g(340, 2, '12 oz frozen bag', 'PRPD confirmed', 'verified'),
    buffalo_sauce: g(354, 3.48, '12 fl oz bottle', 'Local planning price', 'planning'),
    leg_quarter_raw: g(453.592, 0.89, '1 lb', 'PRPD confirmed', 'verified'),
    paprika: g(64, 1.24, '2.25 oz bottle', 'Local planning price', 'planning'),
    chili_powder: g(71, 1.24, '2.5 oz bottle', 'Local planning price', 'planning'),
    cumin: g(57, 1.24, '2 oz bottle', 'Local planning price', 'planning'),
    corn: g(432, 0.98, '15.25 oz can', 'Local planning price', 'planning'),
    cotija: g(283, 5.83, '10 oz package', 'Walmart receipt 2026-07-16', 'verified'),
    cilantro: g(50, 0.46, '1 bunch / about 50g usable', 'Walmart receipt 2026-07-16', 'verified'),
    lime: g(30, 0.33, '1 lime / about 30g juice', 'Local planning price', 'planning'),
    shawarma_bread: g(8, 5, '8-count pack', 'PRPD confirmed', 'verified'),
    pickles: g(680, 3, '24 oz jar', 'Local planning price', 'planning'),
    protein_pasta: g(411, 2.84, '14.5 oz box', 'Walmart receipt 2026-07-16', 'verified', 'Barilla Protein Plus spaghetti'),
    crushed_tomatoes: g(794, 1.5, '28 oz can', 'Earlier PRPD price', 'legacy'),
    breadcrumbs: g(425, 1.77, '15 oz canister', 'Local planning price', 'planning'),
    sweet_chili: g(510, 3.58, '18 oz bottle', 'Earlier PRPD price', 'legacy'),
    soy_sauce: g(444, 3, '15 fl oz bottle', 'Earlier PRPD price', 'legacy'),
    ketchup: g(1077, 3.48, '38 oz bottle', 'Local planning price', 'planning'),
    mustard: g(567, 1, '20 oz bottle', 'Walmart receipt 2026-07-16', 'verified'),
    ladyfingers: g(200, 4, '200g package', 'Local planning price', 'planning'),
    philadelphia_no_bake: g(680, 5.74, '24 oz tub', 'Walmart receipt 2026-07-16', 'verified'),
    simple_truth_yogurt: g(907, 3, '32 oz tub', 'PRPD yogurt rate', 'planning'),
    cocoa: g(227, 3.99, '8 oz container', 'Earlier PRPD price', 'legacy'),
    honey: g(680, 8.97, '24 oz bottle', 'Walmart receipt 2026-07-16', 'verified'),
    oreo_thin: g(26, 3.97, '26-count package', 'Earlier PRPD price', 'legacy'),
    mascarpone: g(227, 4.48, '8 oz tub', 'Local planning price', 'planning'),
    powdered_sugar: g(907, 2.24, '2 lb bag', 'Local planning price', 'planning'),
    protein_mac: g(191, 2.47, '6.75 oz box', 'Walmart reference', 'planning', 'Muscle Mac high protein macaroni and cheese'),
    bbq_sauce: g(510, 3.47, '18 oz bottle', 'Walmart receipt 2026-07-16', 'verified', 'BBQ sauce 18 oz'),
    ny_strip_raw: g(453.592, 10.99, '1 lb', 'PRPD confirmed', 'verified'),
    garlic_powder: g(88, 1.24, '3.1 oz bottle', 'Local planning price', 'planning'),
    onion_powder: g(64, 1.24, '2.25 oz bottle', 'Local planning price', 'planning'),
    dill: g(28, 1.24, '1 oz bottle', 'Local planning price', 'planning'),
    apple_cider_vinegar: g(946, 2.64, '32 fl oz bottle', 'Local planning price', 'planning'),
    meal_container: g(150, 42.99, '150-count case with lids', 'Restaurant Depot receipt 2026-07-16', 'verified'),
    dessert_cup: g(50, 17, '50-count planning pack', 'Planning allowance', 'planning'),
    sauce_cup: g(250, 15, '250-count pack', 'PRPD confirmed', 'verified'),
    paper_bag: g(50, 40, '50-count pack', 'PRPD confirmed', 'verified'),
    printed_label: g(4, 0, 'Avery 5168 sheet / 4 labels', 'Current marginal cost $0', 'verified'),
    kitchen_consumable_allowance: g(1, 0.05, '$0.05 per packed item', 'Approved costing allowance', 'planning'),
    shrimp_raw: g(907.184, 15.96, '2 lb bag', 'Walmart planning reference', 'planning', 'Great Value raw peeled deveined shrimp 2 lb'),
    flour: g(2268, 2.43, '5 lb bag', 'Walmart planning reference', 'planning', 'all purpose flour 5 lb'),
    apple: g(453.592, 2.08, '1 lb', 'Walmart receipt 2026-07-16', 'verified', 'Gala apples'),
    baking_powder: g(230, 2, '8.1 oz can', 'Walmart planning reference', 'planning', 'baking powder'),
    blueberry: g(453.592, 3.12, '16 oz bag', 'Walmart planning reference', 'planning', 'Great Value frozen blueberries 16 oz'),
    carrot: g(907.184, 2.47, '2 lb bag', 'PRPD confirmed', 'verified', 'baby carrots 2 lb'),
    cornstarch: g(454, 2, '1 lb box', 'Earlier PRPD price', 'legacy', 'cornstarch 1 lb'),
    peanut_butter: g(510, 3, '18 oz jar', 'Earlier PRPD price', 'legacy', 'creamy peanut butter 18 oz'),
    cucumber: g(453.592, 0.98, '1 lb', 'Walmart planning reference', 'planning', 'fresh cucumber'),
    hot_sauce: g(354, 3.48, '12 fl oz bottle', 'Walmart planning reference', 'planning', 'Franks RedHot 12 oz'),
    hawaiian_roll: g(12, 2.68, '12-count pack', 'Walmart planning reference', 'planning', 'Great Value Sweet Hawaiian rolls 12 count'),
    green_bell_pepper: g(160, 0.78, '1 pepper / about 160g usable', 'PRPD confirmed', 'verified', 'green bell pepper'),
    beef_strips_raw: g(453.592, 7.99, '1 lb', 'PRPD confirmed', 'verified', 'halal lean beef strips'),
    biscoff_cookie: g(32, 4, '32-count package', 'Earlier PRPD price', 'legacy', 'Lotus Biscoff cookies'),
    biscoff_spread: g(400, 5, '14.1 oz jar', 'Earlier PRPD price', 'legacy', 'Lotus Biscoff cookie butter'),
    chocolate_chips: g(340, 3, '12 oz bag', 'Earlier PRPD price', 'legacy', 'mini semisweet chocolate chips'),
    oats: g(1191, 2.98, '42 oz canister', 'Earlier PRPD price', 'legacy', 'old fashioned rolled oats 42 oz'),
    sesame_oil: g(148, 5, '5 fl oz bottle', 'Earlier PRPD price', 'legacy', 'sesame oil'),
    edamame: g(340, 1.92, '12 oz bag', 'Earlier PRPD price', 'legacy', 'shelled edamame 12 oz'),
    sourdough_slice: g(20, 4, 'loaf / about 20 slices', 'Walmart planning reference', 'planning', 'sourdough bread loaf'),
    sriracha: g(255, 2.38, '9 oz bottle', 'Earlier PRPD price', 'legacy', 'sriracha sauce'),
    banana_pudding_mix: g(30, 1.24, '1 oz packet', 'Walmart planning reference', 'planning', 'sugar free banana pudding mix'),
    sweet_potato: g(453.592, 0.99, '1 lb', 'Walmart planning reference', 'planning', 'fresh sweet potato'),
    mushroom: g(227, 2.08, '8 oz package', 'Walmart planning reference', 'planning', 'white mushrooms 8 oz'),
    zucchini: g(453.592, 1.42, '1 lb', 'PRPD confirmed', 'verified', 'fresh zucchini'),
  };
  return { version: '2026-07-22.2', catalog };
});
