const ORDER_CONFIG = {
  batch: {
    number: 3,
    deliveryDate: 'Saturday, July 25, 2026',
    cutoffIso: '2026-07-22T17:00:00-05:00',
    cutoffLabel: 'Wednesday at 5:00 PM CT',
  },
  policies: {
    minimumOrder: 60,
    freeDeliveryThreshold: 75,
    deliveryFee: 6.99,
    maxQtyPerItem: 50,
    maxTotalItems: 250,
  },
  promotions: {
    codes: [],
  },
  prices: {
    standard: { lean: 10.99, bulk: 12.99 },
    beef: { lean: 13.99, bulk: 15.99 },
    premium: { lean: 21.99, bulk: 26.99 },
    dessert: { single: 6.99 },
  },
  menu: {
    breakfasts: [
      { id: 'b1', name: 'High Protein Omelette', category: 'standard',
        description: 'Eggs, vegetables, fat-free cheese, and sourdough.',
        macros: { cal: 415, protein: 45, carbs: 30, fiber: 3, fat: 13 },
        bulkMacros: { cal: 640, protein: 66, carbs: 51, fiber: 4, fat: 20 }, image: '/assets/images/meals/menu/high-protein-omelette.jpg' },
      { id: 'b2', name: 'Beef Breakfast Skillet', category: 'beef',
        description: 'Seasoned beef, sweet potato, egg, vegetables, and fat-free cheese.',
        macros: { cal: 570, protein: 57, carbs: 28, fiber: 4, fat: 24 },
        bulkMacros: { cal: 760, protein: 77, carbs: 28, fiber: 4, fat: 36 }, image: '/assets/images/meals/menu/beef-breakfast-skillet.jpg' },
      { id: 'b3', name: 'Power Bowl', category: 'standard',
        description: 'Chicken, sweet potato, eggs, and a light yogurt-sriracha finish.',
        macros: { cal: 545, protein: 55, carbs: 25, fiber: 3, fat: 24 },
        bulkMacros: { cal: 690, protein: 73, carbs: 25, fiber: 3, fat: 31 }, image: '' },
      { id: 'b4', name: 'Blueberry Cheesecake Protein Pancakes', category: 'standard',
        description: 'Protein pancakes with blueberry compote and cheesecake-yogurt topping.',
        macros: { cal: 540, protein: 42, carbs: 65, fiber: 3, fat: 12 },
        bulkMacros: { cal: 685, protein: 55, carbs: 83, fiber: 4, fat: 15 }, image: '' },
    ],
    mains: [
      { id: 'm1', name: 'Cheeseburger Hot Pockets', category: 'beef', laterWeek: true,
        description: 'Handmade yogurt dough filled with seasoned beef, cheese, and pickles. Two Lean or three Bulk.',
        macros: { cal: 540, protein: 46, carbs: 71, fiber: 3, fat: 7 },
        bulkMacros: { cal: 815, protein: 69, carbs: 107, fiber: 4, fat: 11 }, image: '' },
      { id: 'm2', name: 'Mexican Streetcorn Chicken Bowl', category: 'standard', laterWeek: true,
        description: 'Chicken, basmati rice, and creamy Mexican street corn with peppers and onions.',
        macros: { cal: 595, protein: 48, carbs: 55, fiber: 3, fat: 21 },
        bulkMacros: { cal: 790, protein: 65, carbs: 72, fiber: 4, fat: 27 }, image: '/assets/images/meals/menu/mexican-streetcorn-chicken-bowl-v2.jpg' },
      { id: 'm3', name: 'Hot Honey Chicken Sliders', category: 'standard',
        description: 'Hot-honey chicken, cheese, pickles, and light sriracha mayo on soft rolls. Two Lean or three Bulk.',
        macros: { cal: 590, protein: 51, carbs: 45, fiber: 1, fat: 21 },
        bulkMacros: { cal: 760, protein: 65, carbs: 61, fiber: 1, fat: 26 }, image: '' },
      { id: 'm4', name: 'Chicken Biryani', category: 'standard', laterWeek: true,
        description: 'Spiced halal chicken and fragrant basmati rice with a cucumber-forward salad.',
        macros: { cal: 505, protein: 43, carbs: 49, fiber: 3, fat: 15 },
        bulkMacros: { cal: 650, protein: 62, carbs: 49, fiber: 3, fat: 22 }, image: '/assets/images/meals/menu/chicken-biryani.jpg' },
      { id: 'm5', name: 'BBQ Chicken Mac & Cheese', category: 'standard', laterWeek: true,
        description: 'BBQ chicken, high-protein mac and cheese, and fat-free mozzarella.',
        macros: { cal: 630, protein: 66, carbs: 54, fiber: 4, fat: 17 },
        bulkMacros: { cal: 765, protein: 85, carbs: 54, fiber: 4, fat: 23 },
        image: '/assets/images/meals/menu/bbq-chicken-mac-and-cheese-lean.jpg',
        images: {
          lean: '/assets/images/meals/menu/bbq-chicken-mac-and-cheese-lean.jpg',
          bulk: '/assets/images/meals/menu/bbq-chicken-mac-and-cheese-bulk.jpg',
        } },
      { id: 'm6', name: 'Korean Bulgogi Beef Bowl', category: 'beef', laterWeek: true,
        description: 'Marinated beef, rice, and stir-fried broccoli, peppers, and carrots.',
        macros: { cal: 655, protein: 48, carbs: 74, fiber: 5, fat: 17 },
        bulkMacros: { cal: 770, protein: 65, carbs: 76, fiber: 5, fat: 21 }, image: '' },
      { id: 'm7', name: 'Garlic Butter Shrimp + Rice', category: 'beef',
        description: 'Garlic-butter shrimp, basmati rice, edamame, zucchini, and lemon.',
        macros: { cal: 500, protein: 50, carbs: 53, fiber: 6, fat: 11 },
        bulkMacros: { cal: 670, protein: 67, carbs: 71, fiber: 7, fat: 15 }, image: '/assets/images/meals/menu/garlic-butter-shrimp.jpg' },
      { id: 'm8', name: 'Premium NY Strip Steak', category: 'premium',
        description: 'New York strip steak with creamy mashed potatoes and broccoli.',
        macros: { cal: 665, protein: 60, carbs: 45, fiber: 7, fat: 28 },
        bulkMacros: { cal: 800, protein: 74, carbs: 48, fiber: 8, fat: 36 },
        image: '/assets/images/meals/menu/premium-ny-strip-steak-lean.jpg',
        images: {
          lean: '/assets/images/meals/menu/premium-ny-strip-steak-lean.jpg',
          bulk: '/assets/images/meals/menu/premium-ny-strip-steak-bulk.jpg',
        } },
    ],
    desserts: [
      { id: 'd1', name: 'Cookie Dough Cup', category: 'dessert',
        description: 'Protein cookie dough with oats, cottage cheese, peanut butter, and chocolate chips.',
        macros: { cal: 520, protein: 38, carbs: 55, fiber: 6, fat: 16 }, image: '' },
      { id: 'd2', name: 'Lotus Biscoff Cheesecake', category: 'dessert',
        description: 'Protein cheesecake with Biscoff cookie butter and a cookie crust.',
        macros: { cal: 395, protein: 40, carbs: 33, fiber: 0, fat: 10 }, image: '' },
      { id: 'd3', name: 'Banana Cream Pie Cup', category: 'dessert',
        description: 'Banana protein cream with a Biscoff cookie finish.',
        macros: { cal: 275, protein: 27, carbs: 36, fiber: 2, fat: 4 }, image: '' },
    ],
  },
};

if (typeof window !== 'undefined') window.PRPD_ORDER_CONFIG = ORDER_CONFIG;
if (typeof module !== 'undefined' && module.exports) module.exports = ORDER_CONFIG;
