const ORDER_CONFIG = {
  batch: {
    number: 2,
    deliveryDate: 'Saturday, July 18, 2026',
    cutoffIso: '2026-07-15T17:00:00-05:00',
    cutoffLabel: 'Wednesday at 5:00 PM CT',
  },
  policies: {
    minimumOrder: 60,
    freeDeliveryThreshold: 75,
    deliveryFee: 6.99,
    maxQtyPerItem: 50,
    maxTotalItems: 250,
  },
  prices: {
    standard: { lean: 10.99, bulk: 12.99 },
    beef: { lean: 13.99, bulk: 15.99 },
    dessert: { single: 6.99 },
  },
  menu: {
    breakfasts: [
      { id: 'b1', name: 'Egg Bites', category: 'standard',
        description: 'Baked egg and cottage cheese bites with melted mozz, spinach, and jalapeño, served with crispy garlic potato hash.',
        macros: { cal: 440, protein: 48, carbs: 24, fiber: 0, fat: 16 },
        bulkMacros: { cal: 615, protein: 69, carbs: 30, fiber: 0, fat: 24 }, image: '/assets/images/meals/egg-bites.jpg' },
      { id: 'b2', name: 'French Toast', category: 'standard',
        description: 'Thick-cut french toast cooked in butter with a rich custard of whole eggs, cottage cheese, and brown sugar. Served with strawberries, banana, and whipped cream.',
        macros: { cal: 520, protein: 40, carbs: 62, fiber: 3, fat: 12 },
        bulkMacros: { cal: 650, protein: 52, carbs: 76, fiber: 4, fat: 14 }, image: '/assets/images/meals/french-toast.jpg?v=20260713' },
      { id: 'b3', name: 'Breakfast Quesadilla', category: 'standard',
        description: 'Grilled quesadilla loaded with seasoned shredded chicken, scrambled eggs, and melted mozz, served with Fage crema and salsa.',
        macros: { cal: 553, protein: 77, carbs: 26, fiber: 0, fat: 16 },
        bulkMacros: { cal: 729, protein: 102, carbs: 32, fiber: 0, fat: 21 }, image: '/assets/images/meals/chicken-quesadillas.jpg' },
      { id: 'b4', name: 'Grilled Cheese Breakfast Burrito', category: 'beef',
        description: 'Saucy seasoned beef, scrambled eggs, and melted mozz wrapped tight in a grilled flour tortilla. Best reheated in the air fryer.',
        macros: { cal: 557, protein: 64, carbs: 32, fiber: 0, fat: 19 },
        bulkMacros: { cal: 749, protein: 89, carbs: 40, fiber: 0, fat: 26 }, image: '' },
    ],
    mains: [
      { id: 'm1', name: 'Butter Chicken', category: 'standard',
        description: 'Tender chicken thigh in a smooth, spiced tomato-yogurt butter sauce, served over basmati rice. Our most popular main.',
        macros: { cal: 484, protein: 57, carbs: 44, fiber: 0, fat: 12 },
        bulkMacros: { cal: 600, protein: 76, carbs: 48, fiber: 0, fat: 15 }, image: '' },
      { id: 'm2', name: 'Halal Cart Chicken + Yellow Rice', category: 'standard',
        description: 'NYC street cart-style chicken over turmeric yellow rice with white garlic sauce and hot sauce on the side.',
        macros: { cal: 500, protein: 58, carbs: 44, fiber: 0, fat: 11 },
        bulkMacros: { cal: 605, protein: 78, carbs: 48, fiber: 0, fat: 14 }, image: '/assets/images/meals/halal-cart-chicken.jpg?v=20260713' },
      { id: 'm3', name: 'Loaded Buffalo Chicken Potato', category: 'standard',
        description: 'Buffalo-tossed diced chicken over crispy roasted potatoes and broccoli. Extra buffalo sauce cup included.',
        macros: { cal: 605, protein: 68, carbs: 48, fiber: 0, fat: 16 },
        bulkMacros: { cal: 720, protein: 86, carbs: 52, fiber: 0, fat: 20 }, image: '' },
      { id: 'm4', name: 'Peri Peri Drumsticks', category: 'standard',
        description: 'Bone-in drumsticks marinated in a house-blended peri peri sauce, oven-roasted on a wire rack, and broiled until charred. Served with rice.',
        macros: { cal: 560, protein: 62, carbs: 42, fiber: 0, fat: 18 },
        bulkMacros: { cal: 690, protein: 81, carbs: 45, fiber: 0, fat: 24 }, image: '' },
      { id: 'm5', name: 'Mexican Streetcorn Chicken Bowl', category: 'standard',
        description: 'Grilled chicken over rice with charred corn, jalapeño crema, cotija cheese, and fresh lime. Smoky, tangy, and bold.',
        macros: { cal: 530, protein: 54, carbs: 44, fiber: 0, fat: 10 },
        bulkMacros: { cal: 660, protein: 73, carbs: 58, fiber: 0, fat: 12 }, image: '' },
      { id: 'm6', name: 'Beef Seekh Kabab Shawarma', category: 'beef',
        description: 'Spiced ground beef seekh kababs oven-baked until charred and juicy, served over rice with a house dipping sauce.',
        macros: { cal: 505, protein: 48, carbs: 36, fiber: 0, fat: 18 },
        bulkMacros: { cal: 605, protein: 60, carbs: 37, fiber: 0, fat: 23 }, image: '/assets/images/meals/beef-seekh-shawarma.jpg' },
      { id: 'm7', name: 'Meatball Arrabbiata Pasta', category: 'beef',
        description: 'Baked beef meatballs tossed in a fiery crushed tomato arrabbiata sauce over high-protein pasta, topped with melted mozz.',
        macros: { cal: 660, protein: 72, carbs: 52, fiber: 0, fat: 20 },
        bulkMacros: { cal: 775, protein: 86, carbs: 58, fiber: 0, fat: 24 }, image: '' },
      { id: 'm8', name: 'Halal Boy Kibble', category: 'beef',
        description: 'Saucy sweet chili ground beef over rice topped with fresh lettuce and mozz, served with mayo, ketchup, and mustard cups.',
        macros: { cal: 545, protein: 56, carbs: 46, fiber: 0, fat: 17 },
        bulkMacros: { cal: 660, protein: 69, carbs: 50, fiber: 0, fat: 21 }, image: '' },
    ],
    desserts: [
      { id: 'd1', name: 'Strawberry Cheesecake', category: 'dessert',
        description: 'Silky high-protein cheesecake filling topped with a sweet strawberry sauce. Creamy, light, and macro-friendly.',
        macros: { cal: 280, protein: 24, carbs: 18, fiber: 4, fat: 6 }, image: '' },
      { id: 'd2', name: 'Chocolate Oreo Mousse', category: 'dessert',
        description: 'Whipped Fage and protein mousse with SF cocoa, topped with a whole Oreo Thin and crushed cookie crumble. Rich and fluffy.',
        macros: { cal: 281, protein: 38, carbs: 18, fiber: 0, fat: 6 }, image: '' },
      { id: 'd3', name: 'High Protein Tiramisu', category: 'dessert',
        description: 'Layers of espresso-soaked ladyfingers and silky cottage cheese cream, dusted with cocoa and powdered sugar.',
        macros: { cal: 295, protein: 38, carbs: 26, fiber: 0, fat: 6 }, image: '' },
    ],
  },
};

if (typeof window !== 'undefined') window.PRPD_ORDER_CONFIG = ORDER_CONFIG;
if (typeof module !== 'undefined' && module.exports) module.exports = ORDER_CONFIG;
