const ORDER_CONFIG = {
  batch: {
    number: 7,
    // Owner approved August 17, 2026. Customer reminders remain separately gated.
    published: true,
    remindersEnabled: true,
    deliveryDate: 'Saturday, August 22, 2026',
    cutoffIso: '2026-08-19T18:00:00-05:00',
    cutoffLabel: 'Wednesday at 6:00 PM CT',
    labelProduction: { madeDate: '2026-08-21', useByDate: '2026-08-24', batchId: 'B7-0821' },
  },
  policies: {
    minimumOrder: 60,
    freeDeliveryThreshold: 85,
    deliveryFee: 9.99,
    deliveryZones: {
      pickup: {
        id: 'pickup',
        label: 'Pickup',
        city: 'Frisco',
        state: 'TX',
        minimumOrder: 50,
        freeDeliveryThreshold: 50,
        deliveryFee: 0,
      },
      core: {
        id: 'core',
        label: 'Local Delivery',
        minimumOrder: 60,
        freeDeliveryThreshold: 85,
        deliveryFee: 9.99,
      },
      regional: {
        id: 'regional',
        label: 'Regional Delivery',
        minimumOrder: 80,
        freeDeliveryThreshold: 125,
        deliveryFee: 12.99,
      },
      extended: {
        id: 'extended',
        label: 'Extended Delivery',
        minimumOrder: 100,
        freeDeliveryThreshold: 150,
        deliveryFee: 14.99,
      },
    },
    maxQtyPerItem: 50,
    maxTotalItems: 250,
  },
  promotions: { remote: true, codes: [] },
  prices: {
    standard: { lean: 10.99, bulk: 12.99 },
    beef: { lean: 13.99, bulk: 15.99 },
    premium: { lean: 21.99, bulk: 26.99 },
    dessert: { single: 6.99 },
    addon: { single: 6.99 },
  },
  plannerOnly: [],
  menu: {
    breakfasts: [
      { id: 'b1', name: 'Blueberry Cheesecake Protein Pancakes', category: 'standard',
        description: 'Protein pancakes with blueberry compote, cheesecake-yogurt topping, and sugar-free maple syrup.',
        macros: { cal: 540, protein: 42, carbs: 65, fiber: 3, fat: 12 }, bulkMacros: { cal: 685, protein: 55, carbs: 83, fiber: 4, fat: 15 }, image: '' },
      { id: 'b2', name: 'PRPD Beef Bacon Breakfast Sandwich', category: 'beef', laterWeek: true,
        description: 'Beef bacon, an egg-and-egg-white patty, cheese, and a PRPD Sweet Heat cup. Lean includes one sandwich with breakfast potatoes; Bulk includes two sandwiches with no potatoes.',
        macros: { cal: 600, protein: 36, carbs: 70, fiber: 4, fat: 20 }, bulkMacros: { cal: 860, protein: 65, carbs: 70, fiber: 2, fat: 35 }, image: '/assets/images/meals/menu/batch-6-2026-08-15/prpd-beef-bacon-breakfast-sandwich.webp', imageTone: 'bright-low' },
      { id: 'b3', name: 'High Protein Omelette', category: 'standard',
        description: 'Eggs, egg whites, vegetables, fat-free cheese, and sourdough.',
        macros: { cal: 400, protein: 42, carbs: 29, fiber: 3, fat: 13 }, bulkMacros: { cal: 625, protein: 63, carbs: 51, fiber: 4, fat: 20 }, image: '/assets/images/meals/menu/high-protein-omelette.jpg' },
      { id: 'b4', name: 'Power Bowl', category: 'standard', laterWeek: true,
        description: 'Seasoned chicken, roasted potatoes, eggs, cheese, and PRPD Sweet Heat sauce.',
        macros: { cal: 595, protein: 52, carbs: 35, fiber: 2, fat: 26 }, bulkMacros: { cal: 735, protein: 71, carbs: 35, fiber: 2, fat: 34 }, image: '' },
    ],
    mains: [
      { id: 'm1', name: 'Hot Honey Chicken Sliders', category: 'standard',
        description: 'Sriracha hot-honey chicken, cheese, house refrigerator pickles, and onion on soft bakery rolls.',
        macros: { cal: 610, protein: 40, carbs: 81, fiber: 2, fat: 14 }, bulkMacros: { cal: 820, protein: 55, carbs: 108, fiber: 3, fat: 19 }, image: '/assets/images/meals/menu/batch-6-2026-08-15/hot-honey-chicken-sliders.webp' },
      { id: 'm2', name: 'Chicken Biryani', category: 'standard', laterWeek: true,
        description: 'Spiced halal chicken layered with fragrant basmati rice, tomato, onion, ginger, garlic, and lemon.',
        macros: { cal: 480, protein: 42, carbs: 43, fiber: 2, fat: 15 }, bulkMacros: { cal: 625, protein: 61, carbs: 43, fiber: 2, fat: 22 }, image: '/assets/images/meals/menu/chicken-biryani.jpg' },
      { id: 'm3', name: 'Butter Chicken', category: 'standard', laterWeek: true,
        description: 'Broth-free butter chicken in a tomato, yogurt, garlic, and ginger sauce with basmati rice.',
        macros: { cal: 620, protein: 52, carbs: 45, fiber: 3, fat: 26 }, bulkMacros: { cal: 865, protein: 74, carbs: 60, fiber: 3, fat: 35 }, image: '/assets/images/meals/menu/butter-chicken-lean.jpg' },
      { id: 'm4', name: 'Sweet Chili Chicken with Vegetable Rice', category: 'standard',
        description: 'Sweet-chili chicken with basmati rice, peas, carrots, garlic, and low-sodium soy sauce.',
        macros: { cal: 510, protein: 43, carbs: 48, fiber: 4, fat: 15 }, bulkMacros: { cal: 695, protein: 59, carbs: 64, fiber: 5, fat: 21 }, image: '/assets/images/meals/menu/sweet-chilli-chicken-thighs.jpg' },
      { id: 'm5', name: 'Meatball Arrabbiata Pasta', category: 'beef', displayCategory: 'Beef', laterWeek: true,
        description: 'Beef meatballs and protein pasta in a slow-simmered tomato arrabbiata sauce with mozzarella.',
        macros: { cal: 640, protein: 63, carbs: 59, fiber: 11, fat: 19 }, bulkMacros: { cal: 775, protein: 77, carbs: 67, fiber: 12, fat: 25 }, image: '/assets/images/meals/menu/meatball-arrabbiata-pasta.jpg', imageTone: 'bright-low' },
      { id: 'm6', name: 'Cajun Garlic Salmon', category: 'beef', displayCategory: 'Seafood', laterWeek: true,
        description: 'Cajun-garlic wild pink salmon with lemon-herb quinoa and roasted green beans.',
        macros: { cal: 540, protein: 55, carbs: 45, fiber: 8, fat: 17 }, bulkMacros: { cal: 720, protein: 74, carbs: 58, fiber: 10, fat: 24 }, image: '' },
      { id: 'm7', name: 'Loaded Buffalo Chicken Potato', category: 'standard', laterWeek: true,
        description: 'Buffalo chicken over a loaded roasted potato with broccoli.',
        macros: { cal: 520, protein: 48, carbs: 40, fiber: 6, fat: 18 }, bulkMacros: { cal: 660, protein: 68, carbs: 40, fiber: 6, fat: 25 }, image: '/assets/images/meals/menu/loaded-buffalo-chicken-potato.jpg' },
      { id: 'm8', name: 'Southwest Beef Taco Bowl', category: 'beef', displayCategory: 'Beef',
        description: 'Seasoned beef, cilantro-lime rice, black beans, corn and peppers, lettuce, cotija, and jalapeno-lime yogurt sauce.',
        macros: { cal: 635, protein: 50, carbs: 59, fiber: 7, fat: 22 }, bulkMacros: { cal: 855, protein: 67, carbs: 78, fiber: 9, fat: 30 }, image: '' },
    ],
    desserts: [
      { id: 'd1', name: 'Baked Strawberry-Lemon Protein Cheesecake', category: 'dessert', description: 'A crustless baked protein cheesecake with a strawberry-lemon swirl.', macros: { cal: 225, protein: 14, carbs: 17, fiber: 1, fat: 11 }, image: '/assets/images/meals/menu/batch-6-2026-08-15/baked-strawberry-lemon-protein-cheesecake-square.webp', imageTone: 'bright-low' },
      { id: 'd2', name: 'Banana Cream Pie Cup', category: 'dessert', description: 'Banana protein cream with a Biscoff cookie finish.', macros: { cal: 275, protein: 27, carbs: 36, fiber: 2, fat: 4 }, image: '' },
      { id: 'd3', name: 'High Protein Tiramisu', category: 'dessert', description: 'A chilled protein tiramisu with mascarpone cream and coffee-soaked ladyfingers.', macros: { cal: 395, protein: 22, carbs: 44, fiber: 1, fat: 15 }, image: '/assets/images/meals/menu/high-protein-tiramisu.jpg', imageTone: 'bright-low' },
    ],
    addons: [
      { id: 'a1', name: 'PRPD Protein Box', category: 'addon', price: 7.99, description: 'Two eggs, halal beef breakfast slices, cheese, a whole mini apple, cucumber, and house jalapeno-lemon yogurt dip.', macros: { cal: 355, protein: 29, carbs: 15, fiber: 2, fat: 20 }, image: '' },
      { id: 'a2', name: 'Mini Chicken Snack Wrap', category: 'addon', price: 7.99, description: 'Two high-fiber tortillas with seasoned chicken, cheese, fresh chopped salad, and house sauce.', macros: { cal: 325, protein: 41, carbs: 29, fiber: 23, fat: 13 }, image: '' },
      { id: 'a3', name: 'Chicken Caesar Crunch Box', category: 'addon', price: 8.99, description: 'Chilled chicken, crisp lettuce, cucumber, Parmesan, house yogurt-Caesar dressing, and croutons packed separately.', macros: { cal: 380, protein: 39, carbs: 18, fiber: 2, fat: 16 }, image: '' },
    ],
  },
};

if (typeof window !== 'undefined') window.PRPD_ORDER_CONFIG = ORDER_CONFIG;
if (typeof module !== 'undefined' && module.exports) module.exports = ORDER_CONFIG;
